### ISSUE TITLE
Correct way for using Java Class RegisterForChanges

### ISSUE THREAD

**Issue by khaledalaneziq8** [eclipse-ditto/ditto-examples#68]
My Task: monitor any changes to a digital twin and execute some java code.

To achieve the above goal I'm trying to use Ditto Java SDK and came across the class: org.eclipse.ditto.examples.changes.RegisterForChanges. The instructions to use [here](https://github.com/eclipse-ditto/ditto-examples/tree/master/java-client) provided two steps:
**Step 1:** _docker-compose up -d_ (Already done and managed to create twins and update twin features as needed via web APIs.)
**Step 2:** _mvn compile exec:java -Dexec.mainClass="org.eclipse.ditto.examples.changes.RegisterForChanges"_ (When I do this I receive build success from Maven).

The question I have is how to utilize the code in the example after successfully building it. I tried the following:
1) Running the resultant JAR by navigating to the target folder and executing the command: 
_java -jar ditto-examples-java-client-0-SNAPSHOT.jar_
Error received: **no main manifest attribute, in ditto-examples-java-client-0-SNAPSHOT.jar**
2) Running the RegisterForChanges class directly by navigating to the target\classes folder and executing the command: 
_java org.eclipse.ditto.examples.changes.RegisterForChanges_
Error received: 
**Error: Unable to initialize main class org.eclipse.ditto.examples.changes.RegisterForChanges
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException**

Any comment on how to use this code to achieve the above task would be highly appreciated. Thanks.

**Comment by thjaeckle** [comment]
Hi.
I assume that something like this should work (from the top of my head without looking at Google) :
```
java -cp ditto-examples-java-client-0-SNAPSHOT.jar org.eclipse.ditto.examples.changes.RegisterForChanges
```

I mainly use those examples directly from my IDE and just run the main classes. 
The examples show some basic use of the client, don't expect much functionality in them.. 

By the way: Did you adjust the `config.properties` to include a proper authentication and endpoint?

**Comment by khaledalaneziq8** [comment]
Thanks for your answer. To answer your question: yes, I only added the following to config.properties (so far using defaults):
endpoint=ws://localhost:8080
### Basic
username=ditto
password=ditto


When I apply your above command I receive the below error related to the jackson library:
**Error: Unable to initialize main class org.eclipse.ditto.examples.changes.RegisterForChanges
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException**

Despite that the pom.xml file includes the jackson dependencies:
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.14.2</version>
        </dependency>
        <dependency>
    		<groupId>com.fasterxml.jackson.core</groupId>
	    	<artifactId>jackson-core</artifactId>
    		<version>2.14.2</version>
	</dependency>
	<dependency>
  		<groupId>com.fasterxml.jackson.core</groupId>
  		<artifactId>jackson-annotations</artifactId>
  		<version>2.14.2</version>
	</dependency>

**Comment by thjaeckle** [comment]
Ah, of course .. you need to add the dependencies to the classpath as well - as the example does not provide an "allinone" .jar

Or simply start from your IDE which should automatically have those dependencies on the classpath.
