### ISSUE TITLE
Issue with rest to websocket connection example 

### ISSUE THREAD

**Issue by gunjan-it-engg** [eclipse-ditto/ditto-examples#69]
**Whenever I try to run Rest to Web-socket example with my running ditto instance I got this kind of error in my localhost machine** 

**Error images given below :-**

![image_2023_03_23T11_04_10_200Z](https://user-images.githubusercontent.com/88319511/227191520-f0199d06-9b98-4c68-a57c-582c2281f873.png)
![image_2023_03_23T11_03_52_577Z](https://user-images.githubusercontent.com/88319511/227191529-bab069de-05e8-4e72-899c-962a64451c91.png)
![image_2023_03_23T10_59_56_512Z](https://user-images.githubusercontent.com/88319511/227191541-7baaeacf-936a-4991-b0cc-336b469a97df.png)

**Comment by gunjan-it-engg** [comment]
dd

**Comment by gunjan-it-engg** [comment]
i'm using api version 1 in eclipse ditto  so now i'm using the api version 2 this will works with api version 2

**Comment by huanancheng** [comment]
Hello, I am currently studying this project and have encountered the same issue. How can I switch API versions

**Comment by huanancheng** [comment]
> Actually I'm using api version 1 in eclipse ditto so I'm getting connection error now I'm using the api version 2 with eclipse-ditto it will works fine with api version 2

Hi@gunjan-it-engg, I am currently studying this project and have encountered the same issue. How can I switch API versions
