### ISSUE TITLE
How to run a rest to websocket example

### ISSUE THREAD

**Issue by huanancheng** [eclipse-ditto/ditto-examples#89]
hi, I am a beginner. May I know how to run the rest to websocket example? Is it possible to directly open index.xml? Do you still need to run the Docker image of Eclipse ditto first?

**Comment by thjaeckle** [comment]
Yes, as documented in the example:
> All we need for this example is a running Eclipse Ditto instance. Please follow the guidelines at the Eclipse Ditto project to get started.

**Comment by huanancheng** [comment]
@thjaeckle  Thank you for your answer. However, when I deployed the Docker container using the Docker Compose up - d command and started it, I encountered an error when I opened the index.xml file. When I clicked the create twin button, I received the message 404 not found.
![image](https://github.com/eclipse-ditto/ditto-examples/assets/89009750/d99b6946-67d4-4afc-b294-32e233262a5b)
![image](https://github.com/eclipse-ditto/ditto-examples/assets/89009750/9c3cbedc-e048-4a1c-84d7-8cab34b02920)
![image](https://github.com/eclipse-ditto/ditto-examples/assets/89009750/5037423b-8678-45ca-acc7-608c23a9b3e7)
Can you tell me how to solve it? Wishing you a wonderful day.

**Comment by thjaeckle** [comment]
The example seems to be using API version 1, which is long gone.
You should be able to adjust it to use URL `/api/2` instead and hopefully it works then.

**Comment by huanancheng** [comment]
@thjaeckle This is a useful method. Thank you very much for your guidance
